version: '3.3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build: .docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - .:/var/www/html
    composer:
        image: composer
        volumes:
            - .:/app
        command: install
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: 'lumen'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'root'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'secret'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'secret'
        ports:
            - '3306:3306'